#! /bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/opt/resmon/startup/resmon.sh
PIDFILE=/var/run/resmon.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
     log_daemon_msg "Starting ResMon"
     if [ ! -f $PIDFILE ]; then
      start_daemon -p $PIDFILE $DAEMON
     fi
     log_end_msg $?
   ;;
  stop)
     log_daemon_msg "Stopping ResMon"
     killproc -p $PIDFILE $DAEMON
     PID=`ps x | grep resmon | head -1 | awk '{print $1}'`
     kill -9 $PID
     log_end_msg $?
   ;;
  status)
     status_of_proc -p $PIDFILE $DAEMON atd && exit 0 || exit $?
   ;;
 *)
   echo "Usage: /etc/init.d/resmon {start|stop|status}"
   exit 1
  ;;
esac

exit 0
